/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_esl_searchforfiles_Video_ImageCodec */

#ifndef _Included_com_esl_searchforfiles_Video_ImageCodec
#define _Included_com_esl_searchforfiles_Video_ImageCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_esl_searchforfiles_Video_ImageCodec
 * Method:    readImage
 * Signature: (Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_esl_searchforfiles_Video_ImageCodec_readImage
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_esl_searchforfiles_Video_ImageCodec
 * Method:    readImageFromMemory
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_esl_searchforfiles_Video_ImageCodec_readImageFromMemory
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_esl_searchforfiles_Video_ImageCodec
 * Method:    writeImage
 * Signature: ([BIIIILjava/lang/String;IIII)I
 */
JNIEXPORT jint JNICALL Java_com_esl_searchforfiles_Video_ImageCodec_writeImage
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jstring, jint, jint, jint, jint);

/*
 * Class:     com_esl_searchforfiles_Video_ImageCodec
 * Method:    writeImageToMemory
 * Signature: ([BIIIILjava/lang/String;IIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_esl_searchforfiles_Video_ImageCodec_writeImageToMemory
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jstring, jint, jint, jint, jint);

/*
 * Class:     com_esl_searchforfiles_Video_ImageCodec
 * Method:    detectFormat
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_esl_searchforfiles_Video_ImageCodec_detectFormat
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_esl_searchforfiles_Video_ImageCodec
 * Method:    canRead
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_esl_searchforfiles_Video_ImageCodec_canRead
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_esl_searchforfiles_Video_ImageCodec
 * Method:    canWrite
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_esl_searchforfiles_Video_ImageCodec_canWrite
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_esl_searchforfiles_Video_ImageCodec
 * Method:    readPSD
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_esl_searchforfiles_Video_ImageCodec_readPSD
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_esl_searchforfiles_Video_ImageCodec
 * Method:    readPSDFromMemory
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_esl_searchforfiles_Video_ImageCodec_readPSDFromMemory
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
