/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_esl_searchforfiles_Video_FFmpegBridge */

#ifndef _Included_com_esl_searchforfiles_Video_FFmpegBridge
#define _Included_com_esl_searchforfiles_Video_FFmpegBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    openVideo
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_openVideo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    closeVideo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_closeVideo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    grabNextFrames
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_grabNextFrames
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    pollVideoFrame
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_pollVideoFrame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    pollAudioFrame
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_pollAudioFrame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    isEOF
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_isEOF
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    seekToSeconds
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_seekToSeconds
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_getWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_getHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    getFrameRate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_getFrameRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    getTotalFrames
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_getTotalFrames
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    getSampleRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_getSampleRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    getAudioChannels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_getAudioChannels
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    getTotalAudioStreams
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_getTotalAudioStreams
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    getVideoCodecName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_getVideoCodecName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    getDurationInSeconds
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_getDurationInSeconds
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    getContainerFormatName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_getContainerFormatName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    getAudioTrackCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_getAudioTrackCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    getAudioTrackLanguage
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_getAudioTrackLanguage
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    setAudioTrack
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_setAudioTrack
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    getSubtitleTrackCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_getSubtitleTrackCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    getSubtitleTrackLanguage
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_getSubtitleTrackLanguage
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    setSubtitleTrack
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_setSubtitleTrack
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    pollSubtitleFrame
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_pollSubtitleFrame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_esl_searchforfiles_Video_FFmpegBridge
 * Method:    pollVideoFramePts
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_esl_searchforfiles_Video_FFmpegBridge_pollVideoFramePts
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
