/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_esl_searchforfiles_Video_VideoThumbnail */

#ifndef _Included_com_esl_searchforfiles_Video_VideoThumbnail
#define _Included_com_esl_searchforfiles_Video_VideoThumbnail
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_esl_searchforfiles_Video_VideoThumbnail
 * Method:    captureThumbnail
 * Signature: (Ljava/lang/String;DII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_esl_searchforfiles_Video_VideoThumbnail_captureThumbnail
  (JNIEnv *, jclass, jstring, jdouble, jint, jint);

/*
 * Class:     com_esl_searchforfiles_Video_VideoThumbnail
 * Method:    saveThumbnail
 * Signature: ([BIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_esl_searchforfiles_Video_VideoThumbnail_saveThumbnail
  (JNIEnv *, jclass, jbyteArray, jint, jint, jstring);

/*
 * Class:     com_esl_searchforfiles_Video_VideoThumbnail
 * Method:    getDuration
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_esl_searchforfiles_Video_VideoThumbnail_getDuration
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
